include: package:flutter_lints/flutter.yaml

linter:
  rules:
    library_private_types_in_public_api: false
    unnecessary_statements: true
    use_build_context_synchronously: true
    always_use_package_imports: true
    depend_on_referenced_packages: false
    avoid_dynamic_calls: true

lintx:
  rules:
    - prefer_adaptive_font_size
    - always_specify_unknown_enum_value
    - prefer_single_line_if_statement
    - avoid_hard_code
    - lines_longer_than_100_chars
    - dispose_animation
    - dispose_change_notifier
    - dispose_gesture_recognizer
    - cancel_timer

analyzer:
  # errors:
  # unused_element: ignore

  # exclude: [lib/**/*.g.dart]

  exclude:
    - lib/**.g.dart
    - lib/model/**/*.g.dart
    - mi_flutter_plugins/**
    - lib/machine/**/*.dart
    - ios/.symlinks/**
    - lib/generated/*.dart
    - lib/test/test_units/ui/page_flow/page_flow_test_pages.r.dart
    - .fvm/**

  plugins:
    - lintx
